### ISSUE TITLE
App crashes complaining about missing packages

### ISSUE THREAD

**Issue by sastels** [cds-snc/repertoire#4]
An app (which uses repertoire) crashed complaining that emotion, styled-system, etc weren't already installed.

**Comment by evadb** [comment]
This is a really good point. I saw the "ideal" as having emotion & styled system installed as dependancies of the overall project and not just this package, so I have them listed as peer dependencies

**Comment by timarney** [comment]
Peer dependencies are the right path here from what I see.  It allows the end user to control the versions of emotion and styled-system.  The console warns about this :)

**Comment by evadb** [comment]
thanks tim!

**Comment by sastels** [comment]
gotcha 💯
